[project]
name = "prompting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.49.0",
    "ollama>=0.6.0",
    "tqdm",
    "httpx",
    "pandas",
]
